# Generated by Django 3.2.3 on 2021-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('priority', models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('green', 'green')], default='yellow', max_length=30, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('ожидает выполнения', 'ожидает выполнения'), ('выполнена', 'выполнена'), ('в процессе выполнения', 'в процессе выполнения')], default='ожидает выполнения', max_length=30, verbose_name='Статус')),
                ('start', models.DateTimeField(verbose_name='Дата и время создания')),
                ('finish', models.DateTimeField(verbose_name='дата и время к которому должна быть выполнена')),
            ],
            options={
                'verbose_name': 'Todo list',
                'verbose_name_plural': 'Todo lists',
            },
        ),
    ]
